feat(examples): update playbooks for new etcd management

diff --git a/examples/playbooks/98.cluster-certificates-renewal.yaml b/examples/playbooks/98.cluster-certificates-renewal.yaml
--- a/examples/playbooks/98.cluster-certificates-renewal.yaml
+++ b/examples/playbooks/98.cluster-certificates-renewal.yaml
@@ -24,90 +24,113 @@
 # In case the certificates are close to expiring, this playbook can be used to renew them.
 
 - name: Renew Kubernetes PKI certificates
-  hosts: master
+  hosts: master,etcd
   become: true
   serial: 1
   tasks:
-    
-    # Get Kubernetes version and modify the output from something like “v1.29.3” to “1.29”.
-    - name: Get the current Kubernetes version
-      shell: |
-        K8S_VERSION=$(kubectl version --short 2>/dev/null | grep 'Server Version:' | awk '{print $3}')
-        if [ -z "$K8S_VERSION" ]; then
-          K8S_VERSION=$(kubectl version 2>/dev/null | grep 'Server Version:' | awk '{print $3}')
-        fi
-        if [ -z "$K8S_VERSION" ]; then
-          echo "ERROR: Unable to get Kubernetes version"
-          exit 1
-        fi
-        echo "$K8S_VERSION" | sed -E 's/^v?([0-9]+\.[0-9]+)\.[0-9]+.*/\1/'
-      register: kubernetes_version
+   # Get Kubernetes version and modify the output from something like "v1.29.4" to "1.29".
+   - name: Get the current Kubernetes version
+     shell: |
+      K8S_VERSION=$(kubectl version --short 2>/dev/null | grep 'Server Version:' | awk '{print $3}')
+      if [ -z "$K8S_VERSION" ]; then
+        K8S_VERSION=$(kubectl version 2>/dev/null | grep 'Server Version:' | awk '{print $3}')
+      fi
+      if [ -z "$K8S_VERSION" ]; then
+        echo "ERROR: Unable to get Kubernetes version"
+        exit 1
+      fi
+      echo "$K8S_VERSION" | sed -E 's/^v?([0-9]+\.[0-9]+)\.[0-9]+.*/\1/'
+     register: kubernetes_version
+     when: inventory_hostname in groups['master']
+  
+   - name: Ensure rsync is installed
+     package:
+       name:
+         - rsync
+       state: latest
 
-    - name: Ensure rsync is installed
-      package:
-        name:
-          - rsync
-        state: latest
-    
-    - name: Backup all Kubernetes certs
-      shell: |
-        (BCK_FOLDER=$HOME/certs-backup/$(date +%Y-%m-%d_%H-%M-%S)
-        mkdir -p $BCK_FOLDER/etc-kubernetes $BCK_FOLDER/etc-etcd-pki \
-        && rsync -av /etc/kubernetes/ $BCK_FOLDER/etc-kubernetes --exclude tmp \
-        && rsync -av /etc/etcd/pki/ $BCK_FOLDER/etc-etcd-pki
-        )
+   - name: Backup Kubernetes certs
+     shell: |
+      (BCK_FOLDER=$HOME/certs-backup/$(date +%Y-%m-%d_%H-%M-%S)
+      mkdir -p $BCK_FOLDER/etc-kubernetes \
+      && rsync -av /etc/kubernetes/ $BCK_FOLDER/etc-kubernetes --exclude tmp
+      )
+     when: inventory_hostname in groups['master']
 
-    - name: Renew all Kubernetes certs
-      shell: |
-        kubeadm certs renew admin.conf \
-        && kubeadm certs renew apiserver \
-        && kubeadm certs renew apiserver-kubelet-client \
-        && kubeadm certs renew controller-manager.conf \
-        && kubeadm certs renew front-proxy-client \
-        && kubeadm certs renew scheduler.conf \
-        && kubeadm certs renew --config=/etc/etcd/kubeadm-etcd.yml --cert-dir=/etc/etcd/pki apiserver-etcd-client \
-        && kubeadm certs renew --config=/etc/etcd/kubeadm-etcd.yml --cert-dir=/etc/etcd/pki etcd-healthcheck-client \
-        && kubeadm certs renew --config=/etc/etcd/kubeadm-etcd.yml --cert-dir=/etc/etcd/pki etcd-peer \
-        && kubeadm certs renew --config=/etc/etcd/kubeadm-etcd.yml --cert-dir=/etc/etcd/pki etcd-server
+   - name: Backup etcd certs
+     shell: |
+      (BCK_FOLDER=$HOME/certs-backup/$(date +%Y-%m-%d_%H-%M-%S)
+      mkdir -p $BCK_FOLDER/etc-etcd-pki \
+      && rsync -av /etc/etcd/pki/ $BCK_FOLDER/etc-etcd-pki
+      )
+     when: inventory_hostname in groups['etcd']
 
-    - name: Renew Kubernetes super-admin.conf (only if Kubernetes version >= 1.29)
-      shell: |
-        kubeadm certs renew super-admin.conf
-      when: kubernetes_version.stdout is version('1.29', '>=')
+   - name: Renew control plane certificates
+     shell: |
+      kubeadm certs renew admin.conf \
+      && kubeadm certs renew apiserver \
+      && kubeadm certs renew apiserver-kubelet-client \
+      && kubeadm certs renew controller-manager.conf \
+      && kubeadm certs renew front-proxy-client \
+      && kubeadm certs renew scheduler.conf
+     when: inventory_hostname in groups['master']
 
-    - name: Restart all control plane components
-      shell: |
-        crictl ps -q --name 'kube-(controller-manager|scheduler|apiserver)' | xargs -r crictl stop
-        crictl ps -a -q --state exited --name 'kube-(apiserver|controller-manager|scheduler)' | xargs -r crictl rm
-        systemctl restart etcd
+   - name: Renew etcd certificates
+     shell: |
+      kubeadm certs renew --config=/etc/etcd/kubeadm-etcd.yml --cert-dir=/etc/etcd/pki apiserver-etcd-client \
+      && kubeadm certs renew --config=/etc/etcd/kubeadm-etcd.yml --cert-dir=/etc/etcd/pki etcd-healthcheck-client \
+      && kubeadm certs renew --config=/etc/etcd/kubeadm-etcd.yml --cert-dir=/etc/etcd/pki etcd-peer \
+      && kubeadm certs renew --config=/etc/etcd/kubeadm-etcd.yml --cert-dir=/etc/etcd/pki etcd-server
+     when: inventory_hostname in groups['etcd']
 
-    - name: Wait for kube-controller-manager to be running
-      shell: crictl ps --name kube-controller-manager | grep -q Running
-      register: kube_controller_manager_status
-      retries: 10
-      delay: 5
-      until: kube_controller_manager_status.rc == 0
+   - name: Renew Kubernetes super-admin.conf (only if Kubernetes version >= 1.29)
+     shell: |
+      kubeadm certs renew super-admin.conf
+     when: 
+       - inventory_hostname in groups['master']
+       - kubernetes_version.stdout is version('1.29', '>=')
 
-    - name: Wait for kube-scheduler to be running
-      shell: crictl ps --name kube-scheduler | grep -q Running
-      register: kube_scheduler_status
-      retries: 10
-      delay: 5
-      until: kube_scheduler_status.rc == 0
+   - name: Restart control plane components
+     shell: |
+      crictl ps -q --name 'kube-(controller-manager|scheduler|apiserver)' | xargs -r crictl stop
+      crictl ps -a -q --state exited --name 'kube-(apiserver|controller-manager|scheduler)' | xargs -r crictl rm
+     when: inventory_hostname in groups['master']
 
-    - name: Wait for kube-apiserver to be running
-      shell: crictl ps --name kube-apiserver | grep -q Running
-      register: kube_apiserver_status
-      retries: 10
-      delay: 5
-      until: kube_apiserver_status.rc == 0
+   - name: Restart etcd
+     shell: systemctl restart etcd
+     when: inventory_hostname in groups['etcd']
 
-    - name: Wait for etcd to be running
-      shell: systemctl is-active etcd --quiet
-      register: etcd_status
-      retries: 10
-      delay: 5
-      until: etcd_status.rc == 0
+   - name: Wait for kube-controller-manager to be running
+     shell: crictl ps --name kube-controller-manager | grep -q Running
+     register: kube_controller_manager_status
+     retries: 10
+     delay: 5
+     until: kube_controller_manager_status.rc == 0
+     when: inventory_hostname in groups['master']
+
+   - name: Wait for kube-scheduler to be running
+     shell: crictl ps --name kube-scheduler | grep -q Running
+     register: kube_scheduler_status
+     retries: 10
+     delay: 5
+     until: kube_scheduler_status.rc == 0
+     when: inventory_hostname in groups['master']
+
+   - name: Wait for kube-apiserver to be running
+     shell: crictl ps --name kube-apiserver | grep -q Running
+     register: kube_apiserver_status
+     retries: 10
+     delay: 5
+     until: kube_apiserver_status.rc == 0
+     when: inventory_hostname in groups['master']
+
+   - name: Wait for etcd to be running
+     shell: systemctl is-active etcd --quiet
+     register: etcd_status
+     retries: 10
+     delay: 5
+     until: etcd_status.rc == 0
+     when: inventory_hostname in groups['etcd']
 
 
 - name: Renew Kubelet certificates
@@ -181,7 +204,7 @@
       shell: |
         find /etc/kubernetes -type f -name '*.conf' |
         egrep -v 'expired' |
-        xargs -L 1 -t -i bash -c 'kubectl config view --raw -o jsonpath="{.users[0].user.client-certificate-data}" --kubeconfig={} | base64 -d | openssl x509 -noout -text | grep After'
+        xargs -L 1 -t -i bash -c 'kubectl config view --kubeconfig=/etc/kubernetes/admin.conf --raw -o jsonpath="{.users[0].user.client-certificate-data}" --kubeconfig={} | base64 -d | openssl x509 -noout -text | grep After'
       register: kconfig_info
     - debug: var=kconfig_info.stdout_lines
 
